#!/usr/bin/env python

import shutil
import os
import subprocess

# Create backup directory, used to store all modification made to files
if not os.path.exists("backup"):
    os.mkdir("backup")

# Init git submodule
ret = subprocess.call(["git submodule update --init --recursive"], shell=True)

# Make symbolic link
vimrc = os.path.expanduser("~/.vimrc")
if not os.path.exists(vimrc):
    os.symlink(os.path.abspath("vimrc"), vimrc)
